### ISSUE TITLE
extract features 

### ISSUE THREAD

**Issue by mathshangw** [qwopqwop200/MaxVIT-pytorch#1]
Thanks for sharing the code .. excuse me if I need to extract the features before the classification layer .. how can I do that with your code, please?

**Comment by qwopqwop200** [comment]
hello.To answer your question first, you can simply delete the last line of MaxVIT. 
https://github.com/qwopqwop200/MaxVIT-pytorch/blob/main/MaxVIT.py#L250
Additionally, as you may be aware, this implementation is informal and does not provide any pre-trained weights.

**Comment by mathshangw** [comment]
Thanks a lot for replying . i did by removing the line 250 from the code but the size of the file 300MB for 7000 images compared to other models it is too large .. does what i did is true ?
```
def extract_features(directory):
    for name in listdir(directory):
        filename=directory + '/' + name
        image= load_img(filename, target_size=(224, 224,3))
        vec=MaxViT(xlarge_args)(preprocess(image).unsqueeze(0))
```

**Comment by mathshangw** [comment]
Thanks a lot for replying. i did this by removing line 250 from the code but the size of the file 300MB for 1000 images compared to other models it is too large .. does what i did is true ?
```
def extract_features(directory):
    for name in listdir(directory):
        filename=directory + '/' + name
        image= load_img(filename, target_size=(224, 224,3))
        vec=MaxViT(xlarge_args)(preprocess(image).unsqueeze(0))
```
